#!/bin/bash
### BEGIN INIT INFO
# Provides:          lpsk
# Required-Start:    docker
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Description:       Lan Party Survival Kit
### END INIT INFO

# set compose file location
composeFile="/opt/lpsk/docker-compose.yml"

# include docker-compose-wrapper script
source /usr/local/bin/docker-compose-wrapper